import { useMemo, useState } from 'react'

export const LANGUAGE_OPTIONS = [
  ['en','English'],['ja','日本語'],['ko','한국어'],['de','Deutsch'],['fr','français'],['it','Italiano'],['es','Español'],['ar','العربية'],['zh-TW','繁體中文'],['zh-CN','简体中文'],
]

const en={
  language:'Language',chooseLanguage:'Choose a language and region',welcome:'Welcome to BXC',username:'Username',password:'Password',login:'Login',noAccount:"I don't have an account?",register:'Register',contact:'Contact customer service',registerEmail:'Register with email',registerPhone:'Register with phone number',phone:'Phone',email:'Email',confirmPassword:'Confirm Password',verificationCode:'Verification Code',send:'Send',signUp:'Sign-up',alreadyAccount:'Already have an account?',invalidLogin:'Invalid username or password.',codeSent:'Verification code sent.',sendingCode:'Sending…',resendCode:'Resend',codeExpiresIn:'Verification code expires in',codeExpired:'Verification code expired. Request a new code.',enterVerificationCode:'Enter the verification code sent to you.',accountCreated:'Account created successfully.',
  logout:'Log out',home:'Home',market:'Market',markets:'Markets',cryptoEtf:'Crypto ETF',loan:'Loan',financial:'Financial',account:'Account',admin:'Admin',
  heroHeadline:'Buy, trade, and hold 350+ cryptocurrencies on the best platform.',availableOn:'Available on the',application:'Application',applicationText:'A mobile-first sandbox interface for exploring account and market features.',cryptoDeposit:'Crypto deposit',cryptoDepositText:'Explore digital-asset workflows in a safe demonstration environment without moving real funds.',averageVolume:'Average 24-hour trading volume',cryptocurrenciesListed:'Cryptocurrencies listed',registeredUsers:'Registered users',newFeatures:'New features are online!',newFeaturesText:'Get to know the latest interface and account improvements.',demoAccount:'Operate with a Demo Account',lowFees:'Demo transactions only',tradeAll:'Trade all assets in one place',tradeAllText:'Explore forex, crypto, stocks, indices and commodities.',lowInterest:'Loan calculator demo',cryptoLoans:'Cryptocurrency loans',cryptoLoansText:'Explore loan scenarios without real lending or collateral.',getStarted:'Get started',featuresWelcome:'Welcome to the BXC sandbox experience. Explore the latest interface modules and simulated market tools.',sandboxNote:'Sandbox only: no real-money deposits, withdrawals, lending, investment returns, or brokerage execution are enabled.',
  products:'Products',investmentLending:'Investment & Lending',company:'Company',aboutUs:'About Us',licenseSupervision:'License Supervision',helpCenter:'Help Center',policies:'Policies',terms:'Terms & Conditions',privacy:'Privacy policy',onlineSupport:'Online Support',legalInfo:'Legal Information',disclaimer:'Disclaimer',riskWarning:'Risk Warning',aboutAdvertising:'About Advertising',rightsReserved:'All rights reserved.',
  tab_crypto:'Crypto',tab_forex:'Forex',tab_stocks:'Stocks',tab_futures:'Futures',name:'Name',chart:'Chart',price:'Price',options:'Options',futures:'Futures',spot:'Spot',time:'Time:',returnLabel:'Return',investment:'Investment:',available:'Available',fee:'Fee',placeDemoOrder:'Place demo order',saving:'Saving…',enterDemoAmount:'Enter a valid demo amount.',demoOrderSaved:'Demo order saved.',demoTradeDisclaimer:'Simulation only. Demo orders do not represent real trades, investments, returns, or ownership of financial assets.',spotPrice:'Spot price',
  verifyIdentityLoan:'Verify your account profile to access the loan calculator demo.',startVerification:'Start verification',wantBorrow:'I want to borrow…',loanRange:'Demo amount must be between 1,000 - 100,000 USDT',loanTerm:'Loan term (Days):',dailyInterest:'Illustrative daily interest rate:',totalInterest:'Illustrative total interest:',loanDemoNotice:'This calculator is educational only and does not create a loan or financial obligation.',simulateBorrow:'Simulate borrowing',verifyFirst:'Complete the verification review first.',demoLoanRecorded:'Loan scenario calculated. No real loan was created.',verificationSubmitted:'Verification request submitted for administrator review.',firstName:'First name:',lastName:'Last name:',gender:'Female / Male:',birthdate:'Birthdate:',country:'Country:',address:'Address:',enterPhone:'Enter your phone number…',document:'Document:',passport:'Passport',idCard:'Identity card',continue:'Continue',verificationPrivacy:'For this sandbox, identity document files are not uploaded or stored. The administrator only receives a verification-review request.',
  financialProducts:'Financial Products',productList:'Product List',myInvestments:'My Investments',product:'Product',cycleDays:'Cycle (Days)',dailyRate:'Daily Rate',investmentRange:'Investment Range (USDT)',noDemoInvestments:'No demo investments yet',demoFinancialDisclaimer:'This section is a visual sandbox. It does not accept deposits, promise returns, or create investment contracts.',close:'Close',
  tradingBalance:'Trading account balance',spotBalance:'Spot account balance',financeBalance:'Finance account balance',accountTransfer:'Account Transfer',flashExchange:'Flash Exchange',depositWithdrawal:'Deposit & Withdrawal',bankCardWithdrawal:'Bank Card Withdrawal',order:'Order',order_0:'All orders',order_1:'Contracts',order_2:'Options',order_3:'Crypto ETF',order_4:'Wallet Income',order_5:'My Investments',order_6:'Spot Orders',noMoreData:'No more data',settings:'Settings',accountVerification:'Account Verification',verified:'Verified',notVerified:'Not verified',inviteFriends:'Invite Your Friends',contactWhatsapp:'Contact us (WhatsApp)',contactOnline:'Contact us (Online)',helpCenterFaq:'Help Center (FAQs)',notification:'Notification',changePassword:'Change Password',changeLanguage:'Change Language',currentPassword:'Current password',newPassword:'New password',passwordChanged:'Password changed successfully.',save:'Save',demoMode:'Demo mode',demoOnlyMessage:'This action is intentionally disabled in the sandbox because it would move or simulate real user funds.',alreadyVerified:'This account has already been marked verified by an administrator.',verificationAdminReview:'Verification requests are reviewed from the staff dashboard.',
  adminDashboard:'Administration dashboard',adminDashboardSub:'Manage user access, verification status, and review sandbox activity.',totalUsers:'Total users',active:'Active',suspended:'Suspended',demoOrders:'Demo orders',searchAccounts:'Search username, email, phone or account code…',accounts:'accounts',accountCode:'Account',staff:'Staff',verification:'Verification',status:'Status',joined:'Joined',actions:'Actions',suspend:'Suspend',restore:'Restore',verify:'Verify',unverify:'Unverify',refresh:'Refresh',loading:'Loading…',adminSafetyTitle:'Financial-safety boundary',adminSafetyText:'The admin dashboard can manage account access and verification status, but it cannot credit balances, approve real withdrawals, manipulate returns, or move user funds.',
}

const translations={
  en,
  fr:{...en,language:'Langue',chooseLanguage:'Choisissez une langue et une région',welcome:'Bienvenue sur BXC',username:"Nom d’utilisateur",password:'Mot de passe',login:'Connexion',noAccount:"Je n’ai pas de compte ?",register:"S’inscrire",contact:'Contacter le service client',registerEmail:"S’inscrire avec e-mail",registerPhone:"S’inscrire avec un numéro de téléphone",phone:'Téléphone',email:'E-mail',confirmPassword:'Confirmer le mot de passe',verificationCode:'Code de vérification',send:'Envoyer',sendingCode:'Envoi…',resendCode:'Renvoyer',codeExpiresIn:'Le code de vérification expire dans',codeExpired:'Le code de vérification a expiré. Demandez un nouveau code.',enterVerificationCode:'Saisissez le code de vérification reçu.',signUp:"S’inscrire",alreadyAccount:'Vous avez déjà un compte ?',logout:'Déconnexion',home:'Accueil',market:'Marché',markets:'Marchés',loan:'Prêt',financial:'Finance',account:'Compte',newFeatures:'Les nouvelles fonctionnalités sont en ligne !',settings:'Paramètres',accountVerification:'Vérification du compte',changePassword:'Changer le mot de passe',changeLanguage:'Changer la langue',adminDashboard:'Tableau de bord administrateur'},
  de:{...en,language:'Sprache',chooseLanguage:'Sprache und Region auswählen',welcome:'Willkommen bei BXC',username:'Benutzername',password:'Passwort',login:'Anmelden',register:'Registrieren',logout:'Abmelden',home:'Startseite',market:'Markt',markets:'Märkte',loan:'Kredit',financial:'Finanzen',account:'Konto',settings:'Einstellungen'},
  it:{...en,language:'Lingua',chooseLanguage:'Scegli lingua e regione',welcome:'Benvenuto su BXC',username:'Nome utente',password:'Password',login:'Accedi',register:'Registrati',logout:'Esci',home:'Home',market:'Mercato',markets:'Mercati',loan:'Prestito',financial:'Finanza',account:'Account',settings:'Impostazioni'},
  es:{...en,language:'Idioma',chooseLanguage:'Elige un idioma y una región',welcome:'Bienvenido a BXC',username:'Usuario',password:'Contraseña',login:'Iniciar sesión',register:'Registrarse',logout:'Cerrar sesión',home:'Inicio',market:'Mercado',markets:'Mercados',loan:'Préstamo',financial:'Finanzas',account:'Cuenta',settings:'Ajustes'},
  ja:{...en,language:'言語',chooseLanguage:'言語と地域を選択',welcome:'BXCへようこそ',username:'ユーザー名',password:'パスワード',login:'ログイン',register:'登録',logout:'ログアウト',home:'ホーム',market:'マーケット',markets:'マーケット',loan:'ローン',financial:'金融',account:'アカウント',settings:'設定'},
  ko:{...en,language:'언어',chooseLanguage:'언어 및 지역 선택',welcome:'BXC에 오신 것을 환영합니다',username:'사용자 이름',password:'비밀번호',login:'로그인',register:'회원가입',logout:'로그아웃',home:'홈',market:'마켓',markets:'마켓',loan:'대출',financial:'금융',account:'계정',settings:'설정'},
  ar:{...en,language:'اللغة',chooseLanguage:'اختر اللغة والمنطقة',welcome:'مرحبًا بك في BXC',username:'اسم المستخدم',password:'كلمة المرور',login:'تسجيل الدخول',register:'إنشاء حساب',logout:'تسجيل الخروج',home:'الرئيسية',market:'السوق',markets:'الأسواق',loan:'قرض',financial:'المالية',account:'الحساب',settings:'الإعدادات'},
  'zh-TW':{...en,language:'語言',chooseLanguage:'選擇語言和地區',welcome:'歡迎來到 BXC',username:'使用者名稱',password:'密碼',login:'登入',register:'註冊',logout:'登出',home:'首頁',market:'市場',markets:'市場',loan:'貸款',financial:'金融',account:'帳戶',settings:'設定'},
  'zh-CN':{...en,language:'语言',chooseLanguage:'选择语言和地区',welcome:'欢迎来到 BXC',username:'用户名',password:'密码',login:'登录',register:'注册',logout:'退出登录',home:'首页',market:'市场',markets:'市场',loan:'贷款',financial:'金融',account:'账户',settings:'设置'},
}

export function useI18n(){
  const [language,setLanguageState]=useState(()=>localStorage.getItem('bxc-language')||'en')
  const setLanguage=(next)=>{localStorage.setItem('bxc-language',next);setLanguageState(next);document.documentElement.lang=next;document.documentElement.dir=next==='ar'?'rtl':'ltr'}
  const t=useMemo(()=>translations[language]||en,[language])
  return {language,setLanguage,t}
}
